language: cpp

sudo: false

cache:
  apt: true
    
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

# Upgrade gcc to gcc5
before_script:
  - export CXX=/usr/bin/g++-5

install:
  - cd ${TRAVIS_BUILD_DIR}
  - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - test/runTests
