language: cpp

install:
  - cd ${TRAVIS_BUILD_DIR}
  - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  - cmake --version
# TODO: upgrade gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - test/runTests
